# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bul_cbp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_contact_email', models.EmailField(max_length=254)),
                ('has_public_code_url', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', max_length=20)),
                ('public_code_url', models.URLField()),
                ('contains_lightweight_data_reporting', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', max_length=20)),
                ('accessability_check_run', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', max_length=20)),
                ('project_contact_email_CHECKED', models.DateField()),
                ('has_public_code_url_CHECKED', models.DateField()),
                ('public_code_url_CHECKED', models.DateField()),
                ('contains_lightweight_data_reporting_CHECKED', models.DateField()),
                ('accessability_check_run_CHECKED', models.DateField()),
                ('code_is_supported', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', help_text='eg: uses long-term-release version or later', max_length=20)),
                ('code_is_supported_CHECKED', models.DateField()),
                ('https_enforced', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', max_length=20)),
                ('https_enforced_CHECKED', models.DateField()),
                ('admin_links_shib_protected', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='n/a', max_length=20)),
                ('admin_links_shib_protected_CHECKED', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
