# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0002_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='accessability_check_run',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='accessability_check_run_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='admin_links_shib_protected',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='admin_links_shib_protected_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='code_versioned',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='code_versioned_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='contains_lightweight_data_reporting',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='contains_lightweight_data_reporting_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='data_discoverable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='information accessible by discovery-application', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='data_discoverable_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='django_session_data_expired',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text="if django session-data is stored in db, it's auto-deleted via cron", max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='django_session_data_expired_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='framework_supported',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='eg: uses long-term-release version or later', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='framework_supported_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_public_code_url',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for whether there is a public url to code'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_sitechecker_entry',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_sitechecker_entry_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='https_enforced',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='https_enforced_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='logs_rotated',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='logs_rotated_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='patron_data_expiration_process',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='if patron data is captured, there is an implemented process for identifying info to be deleted', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='patron_data_expiration_process_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='project_contact_email_CHECKED',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='public_code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for the url entered in this web-app'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='responsive',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='looks/works right on desktop & mobile-devices', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='responsiveness_CHECKED',
            field=models.DateField(blank=True),
        ),
    ]
