# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0002_tracker'),
    ]

    operations = [
    ]
