# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0003_auto_20171106_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='code_is_supported',
            new_name='framework_supported',
        ),
    ]
