# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0003_auto_20180115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='project_contact_email_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
    ]
