# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0005_auto_20180115_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='score',
            field=models.IntegerField(blank=True, help_text='auto-calculated', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='accessability_check_run_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='admin_links_shib_protected_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='code_versioned_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='contains_lightweight_data_reporting_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='data_discoverable_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='django_session_data_expired_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='framework_supported_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for whether there is a public url to code', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_sitechecker_entry_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='https_enforced_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='logs_rotated_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='patron_data_expiration_process_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for the url entered in this web-app', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='responsiveness_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
    ]
