# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0005_auto_20171106_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='slug',
            field=models.SlugField(default='init'),
        ),
    ]
