# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0006_auto_20180214_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='score',
            field=models.IntegerField(blank=True, help_text='auto-calculated, not editable', null=True),
        ),
    ]
