# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bul_cbp_app', '0008_auto_20190301_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='emails_admin_on_error',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='tracker',
            name='emails_admin_on_error_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='vulnerabilities_fixed',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='github `potential security vulnerabilities` fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='tracker',
            name='vulnerabilities_fixed_CHECKED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='framework_supported',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('n/a', 'not-applicable')], default='no', help_text='uses latest version of a supported long-term-release', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='has_public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for the drop-down menu for whether there _is_ a public url to code', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='public_code_url_CHECKED',
            field=models.DateField(blank=True, help_text='check-date for the _accuracy_ of the public url entered', null=True),
        ),
    ]
